---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cnpg-system/
  - ./emqx-operator/
  - ./media/
  - ./network/
  - ./gpu-system/
  - ./gateway/
  - ./resume/
  - ./vaultwarden/
  - ./zigbee/
